### ISSUE TITLE
Post PLZ Verzeichniss

### ISSUE THREAD

**Issue by crimsdings** [bresu/oe_gemeinden#1]
Hallo,

Falls Reddit Comment untergeht: 

Die Post hat unter https://www.post.at/g/c/postlexikon ein PLZ Verzeichniss - könnte helfen.

Im Verzeichnis "PLZ-Bestimmungsort" finden Sie die richtigen Bezeichnungen der Bestimmungsorte zu allen gültigen Postleitzahlen in Österreich. So verwenden Sie bei der Adressierung garantiert die richtige Postleitzahlen-Ort-Kombination.

Das Postleitzahlenverzeichnis beinhaltet alle Postleitzahlen Österreichs - gültige und historische - sowie die dazugehörigen Postleitzahlen-Namen.

Auch auf der RTR unter https://www.rtr.at/de/inf/odPLZ zu finden.

PS: Json wäre auch schön

**Comment by bresu** [comment]
Alles klar, ich denke mir ist ein Fehler unterlaufen beim entfernen von Duplikaten (habe nämlich mit der Liste aller ORTSCHAFTEN gearbeitet) Habe jetzt die Liste der PLZs der Gemeinden und füge das ein & überprüfe noch schnell ob das passt.
Danke für die Unterstützung & Hilfe!

Bei JSON kenn ich mich leider nicht so gut aus, aber werde das auf die ToDo Liste schreiben!

**Comment by crimsdings** [comment]
spitze wenns hilft. CSV to JSON am leichtesten -> https://csvjson.com/csv2json

**Comment by bresu** [comment]
Alles klar, ich machs zur sicherheit mit ```
pandas module ``` über Python und dann online mit dem converter und schau dann, obs da unterschiede gibt

**Comment by bresu** [comment]
So, habe JSON jetzt auch hochgeladen!
